module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  mode: "jit",
  theme: {
    //screens: {},
    animationDelay: {
      500: "500ms",
      1000: "1000ms",
      1500: "1500ms",
      2000: "2000ms",
      2500: "2500ms",
      3000: "3000ms",
      3500: "3500ms",
      4000: "4000ms",
      4500: "4500ms",
      5000: "5000ms",
      5500: "5500ms",
      6000: "6000ms",
      6500: "6500ms",
      7500: "7500ms",
      8000: "8000ms",
    },
    extend: {
      fontFamily: {
        // Art font
        alexBrush: "Alex Brush",
        allura: "Allura",
        arimaMadurai: "Arima Madurai",
        arizonia: "Arizonia",
        badScript: "Bad Script",
        charm: "Charm",
        chewy: "Chewy",
        cinzelDecorative: "Cinzel Decorative",
        dancingScript: "Dancing Script",
        festive: "Festive",
        frederickatheGreat: "Frederickathe Great",
        fugazOne: "Fugaz One",
        gluten: "Gluten",
        greatVibes: "Great Vibes",
        gwendolyn: "Gwendolyn",
        herrVonMuellerhoff: "Herr Von Muellerhoff",
        homemadeApple: "Homemade Apple",
        hurricane: "Hurricane",
        imperialScript: "Imperial Script",
        inspiration: "Inspiration",
        italianno: "Italianno",
        kaushanScript: "Kaushan Script",
        lobster: "Lobster",
        lobsterTwo: "Lobster Two",
        loveLight: "Love Light",
        luxuriousScript: "Luxurious Script",
        marckScript: "Marck Script",
        meaCulpa: "Mea Culpa",
        meddon: "Meddon",
        merienda: "Merienda",
        monsieurLaDoulaise: "Monsieur La Doulaise",
        mrDafoe: "Mr Dafoe",
        mrDeHaviland: "Mr De Haviland",
        mrsSaintDelafield: "Mrs Saint Delafield",
        neonderthaw: "Neonderthaw",
        ole: "Ole",
        pacifico: "Pacifico",
        parisienne: "Parisienne",
        petitFormalScript: "Petit Formal Script",
        philosopher: "Philosopher",
        pinyonScript: "Pinyon Script",
        playball: "Playball",
        praise: "Praise",
        satisfy: "Satisfy",
        seaweedScript: "Seaweed Script",
        shrikhand: "Shrikhand",
        smooch: "Smooch",
        tangerine: "Tangerine",
        theNautigal: "The Nautigal",
        twinkleStar: "Twinkle Star",
        unicaOne: "Unica One",
        unifrakturMaguntia: "UnifrakturMaguntia",

        //Text Font
        balooBhaijaan2: "Baloo Bhaijaan 2",
        comfortaa: "Comfortaa",
        comicNeue: "Comic Neue",
        delius: "Delius",
        forum: "Forum",
        gruppo: "Gruppo",
        handlee: "Handlee",
        mali: "Mali",
        montserrat: "Montserrat",
        poiretOne: "Poiret One",
        quintessential: "Quintessential",
        sniglet: "Sniglet",
      },
      colors: {
        gold: "#BC9C22",
      },
      animation: {
        //animation: name time func delay iteration dir fill play,
        // animation: none 0s ease 0s 1 normal none running,
        wiggle: "wiggle 1s ease-in-out infinite",
        fadeIn: "fadeIn 1500ms ease-in-out both ",
        fadeInUp: "fadeInUp 1500ms ease-in-out both ",
        fadeInDown: "fadeInDown 1500ms ease-in-out both ",
        fadeInLeft: "fadeInLeft 1500ms ease-in-out both ",
        fadeInRight: "fadeInRight 1500ms ease-in-out both ",
        fadeOut: "fadeOut 500ms ease-in-out both ",
        zoomIn: "zoomIn 1500ms ease-in-out both ",
        beat: "beat 1500ms ease-in-out infinite",
      },
      keyframes: {
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        fadeOut: {
          "0%": { opacity: 1 },
          "100%": { opacity: 0 },
        },
        fadeIn: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        fadeInUp: {
          "0%": { opacity: 0, transform: "translateY(-25%)" },
          "100%": { opacity: 1 },
        },
        fadeInDown: {
          "0%": { opacity: 0, transform: "translateY(25%)" },
          "100%": { opacity: 1 },
        },
        fadeInLeft: {
          "0%": { opacity: 0, transform: "translateX(-25%)" },
          "100%": { opacity: 1 },
        },
        fadeInRight: {
          "0%": { opacity: 0, transform: "translateX(25%)" },
          "100%": { opacity: 1 },
        },
        zoomIn: {
          "0%": { opacity: 0, transform: "scale(70%)" },
          "100%": { opacity: 1 },
        },
        beat: {
          "0%": { transform: "scale(95%)" },
          "70%": { transform: "scale(100%)" },
          "100%": { transform: "scale(95%)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animation-delay")],
};
